### PR TITLE
obfuscate the output of the config during cmd inititialization debug log

### LINKED ISSUE #21: User credentials in log output
**What happened**:
When KAI is deployed with log_level set to 'debug', the application config data, including user credentials, is output to log in plain-text.
**What you expected to happen**:
Sensitive data should be redacted/hashed in the log output.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy KAI with log level set to 'debug' and view pod logs.
**Anything else we need to know?**:

**Environment**:
- kai version (use `kai version`): v0.2.0
- OS (e.g: `cat /etc/os-release` or similar): amazonlinux

[kai-logs.log](https://github.com/anchore/kai/files/5960176/kai-logs.log)

### PR DESCRIPTION
**Pull request by dakaneye**
Obfuscates the config YAML string when it's logged (debug level) WRT sensitive keys
Fixes #21 
Signed-off-by: Samuel Dacanay <sam.dacanay@anchore.com>

### CODE REVIEW

**Review by luhring — COMMENTED** [review]
My suggestion would be to prevent the secrets' leakage further upstream if possible. I was curious how Syft was doing this, and I see that the config's `String()` method overrides the values in question before any further transformation takes place: https://github.com/anchore/syft/blob/main/internal/config/config.go#L143-L161

This way, we have precise control over the values to withhold, rather than relying on our "deny list" of fields to match a string value.

File: Makefile [hunk 1]
```diff
@@ -15,7 +15,7 @@ RESET := $(shell tput -T linux sgr0)
 TITLE := $(BOLD)$(PURPLE)
 SUCCESS := $(BOLD)$(GREEN)
 # the quality gate lower threshold for unit test total % coverage (by function statements)
-COVERAGE_THRESHOLD := 60
```
Comment (dakaneye) [inline Makefile:18]: to be clear, this is unit test coverage threshold, not a holistic view of test coverage (integration tests should cover almost every part of the app)

Comment (dakaneye) [reply Makefile:18]: Apparently me adding some unit tests to the config package lowered the coverage because previously there hadn't been any unit tests there (which was ignored from the coverage report)

File: internal/config/config.go [hunk 2]
```diff
@@ -26,6 +28,8 @@ import (
 	"strings"
 )
 
+const Redacted = "******"
```
Comment (luhring) [inline internal/config/config.go:31]: I LOVE extracting this string out as a constant!! 💯

Comment (luhring) [reply internal/config/config.go:31]: Nit: since this constant is used only in this package, it can be unexported

File: internal/config/config.go [hunk 3]
```diff
@@ -228,3 +232,29 @@ func readConfig(v *viper.Viper, configPath string) error {
 
 	return fmt.Errorf("application config not found")
 }
+
+func (cfg Application) String() string {
```
Comment (luhring) [inline internal/config/config.go:236]: Nice!

File: cmd/cmd.go [hunk 4]
```diff
@@ -79,11 +78,5 @@ func initLogging() {
...
 
 func logAppConfig() {
-	appCfgStr, err := yaml.Marshal(&appConfig)
-
-	if err != nil {
-		log.Debugf("Could not display application config: %+v", err)
-	} else {
-		log.Debugf("Application config:\n%+v", string(appCfgStr))
-	}
+	log.Debugf("Application config:\n%+v", appConfig.String())
```
Comment (luhring) [inline cmd/cmd.go:81]: Something cool about Go:

By adding a receiver method onto a type (in this case, the `Application` struct type) with the signature _`String() string`_, you've actually implemented the `fmt.Stringer` interface! Stringers are cool, because the `fmt` functions treat them just as if they were plain old strings (by automatically calling `.String()` on your argument) when you use `%s`.

That means that this line of code can be simplified (a tad) to this:

```go
log.Debugf("Application config:\n%s", appConfig)
```

**Review by luhring — APPROVED** [review]
🎉
